In [1]:
import pandas as pd
filePath = ("/content/drive/MyDrive/Face_Recognition_Project/Spotify_millsongdata.csv")
df = pd.read_csv(filePath)
df

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
...,...,...,...,...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [2]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [3]:
df.shape

(57650, 4)

In [4]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [5]:
df = df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [6]:
df.head(10)

,artist,song,text
0,Kinks,Funny Face,You're walking 'round in my memory \r\nThat o...
1,Genesis,It's Gonna Get Better,"Hold out, just keep on hoping against hope it'..."
2,Journey,One More,"Wicked prophets kill, speaking his name \r\nI..."
3,Keith Urban,Hit The Ground Running,"Well, if you ever said goodbye I wouldn't wast..."
4,Hank Snow,For Now And Always,For now and always \r\nI'll hold you tight da...
5,Insane Clown Posse,Neden Game,"""Let's meet contestant number one \r\nHe's a ..."
6,Matt Redman,Mission's Flame,Verse 1 \r\nLet worship be the fuel for missi...
7,Uncle Kracker,I Don't Know,I'm nothing fancy \r\nI'm nothing special tha...
8,Quicksilver Messenger Service,Rebel,"I am a good old Rebel, that's exactly what I a..."
9,Hillsong,Our King Has Come,"Come, come rejoice this day \r\nCome and see ..."

In [7]:
df['text'][0]

"You're walking 'round in my memory  \r\nThat only gets stronger and stronger  \r\nSmudged mascara and pill-shaped eyes  \r\nEverything you want was bought with lies.  \r\nBut what can I do about it  \r\nThe say you won't last any longer  \r\nAll the gates of love you won't walk through  \r\nThe only gates you see are colored blue.  \r\nI see you peering through frosted windows  \r\nEyes don't smile, all they do is cry  \r\nFunny Face, she's all right  \r\nFunny Face, she's all right  \r\nFunny Face, she's all right  \r\nOh how can I live without her  \r\nThe doctors won't let me see her  \r\nBut I can catch a glimpse through the doorway  \r\nOf the girl that I love and care for  \r\nI see you peering through frosted windows  \r\nEyes don't smile, all they do is cry  \r\nFunny Face, she's all right  \r\nFunny Face, she's all right  \r\nFunny Face, she's all right\r\n\r\n"

In [8]:
df.shape

(5000, 3)

In [9]:
df['text'] = df['text'].str.lower().replace(r'^\w\s',' ').replace(r'\n',' ',regex = True)

In [10]:
df

,artist,song,text
0,Kinks,Funny Face,you're walking 'round in my memory \r that on...
1,Genesis,It's Gonna Get Better,"hold out, just keep on hoping against hope it'..."
2,Journey,One More,"wicked prophets kill, speaking his name \r in..."
3,Keith Urban,Hit The Ground Running,"well, if you ever said goodbye i wouldn't wast..."
4,Hank Snow,For Now And Always,for now and always \r i'll hold you tight day...
...,...,...,...
4995,Leonard Cohen,Be For Real,are you back in my life to stay \r or is it j...
4996,Morrissey,America Is Not The World,"america, your head's too big \r because ameri..."
4997,Slayer,Hallowed Point,high velocity bullet at close range \r can da...
4998,Green Day,Jinx,i fucked up again it's all my fault. \r so tu...
4999,Devo,Ton O' Love,when love takes a back seat to life \r when a...

In [11]:
df.tail(5)

,artist,song,text
4995,Leonard Cohen,Be For Real,are you back in my life to stay \r or is it j...
4996,Morrissey,America Is Not The World,"america, your head's too big \r because ameri..."
4997,Slayer,Hallowed Point,high velocity bullet at close range \r can da...
4998,Green Day,Jinx,i fucked up again it's all my fault. \r so tu...
4999,Devo,Ton O' Love,when love takes a back seat to life \r when a...

In [12]:
import nltk
from nltk.stem.porter import PorterStemmer

In [13]:
stemmer = PorterStemmer()

In [14]:
def token(txt):
 token = nltk.word_tokenize(txt)
 a = [stemmer.stem(w) for w in token]
 return " ".join(a)

In [15]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
tfid = TfidfVectorizer(analyzer='word', stop_words='english')

In [17]:
matrix = tfid.fit_transform(df['text'])

In [18]:
similer = cosine_similarity(matrix)

In [19]:
similer[1]

array([0.01039473, 1.        , 0.03214091, ..., 0.        , 0.01014488,
       0.04736203])

In [23]:
df[df['song']=='Be For Real'].index[0]

np.int64(4995)

In [24]:
def recommender(song_name):
  idx = df[df['song']==song_name].index[0]
  distance = sorted(list(enumerate(similer[idx])) , reverse=True ,key =lambda x:x[1])
  song = []
  for s_id in distance[1:21]:
    song.append(df.iloc[s_id[0]].song)
  return song

In [26]:
recommender("Be For Real")

['I Just Want To Make Love To You',
 'Dont You Want Me',
 'Pretty Baby',
 "Don't Forget About Us",
 'Baby One More Time',
 'Baby Hold On',
 'Street Hassle: Slip Away',
 "Can't Take My Eyes Off You",
 'Baby Love',
 "Don't Look Back",
 'Just Some Love',
 "Baby, Please Don't Go",
 'Brightest Star',
 'Come Back',
 'Without You',
 'Love Is',
 'Fastlove',
 'I Know',
 "Can't Turn You Loose",
 'The Real Me']

In [27]:
import pickle

In [28]:
pickle.dump(similer, open('similarity','wb'))

In [29]:
pickle.dump(df, open('df','wb'))

In [30]:
df.to_csv("cluster_df.csv")